### ISSUE TITLE
Not repsonsive Header

### ISSUE THREAD

**Issue by rainbowdashlabs** [Taminoful/debug-paste-frontend#1]
The header is not full responsive.

![image](https://chojos.lewds.de/YplQtW9aZ9.png)

Thanks <3

**Comment by Taminoful** [comment]
This issue is solved in the lastest release see tag [v1.1.1](https://github.com/Taminoful/debug-paste-frontend/releases/tag/v1.1.1).

**Comment by rainbowdashlabs** [comment]
<3
